--Selecting all the data
SELECT * FROM DEATH_CAUSES;


--Selecting specific coulmns that i will be working with
SELECT ENTITY, YEAR , SELF_HARM, INTERPERSONAL_VIOLENCE, MALARIA, HIV_AIDS, ROAD_INJURIES, ALCOHOL_USE_DISORDERS, DRUG_USE_DISORDERS 
FROM DEATH_CAUSES;


--SLECTING 2019 data
SELECT ENTITY, YEAR , SELF_HARM, INTERPERSONAL_VIOLENCE, MALARIA, HIV_AIDS, ROAD_INJURIES, ALCOHOL_USE_DISORDERS, DRUG_USE_DISORDERS 
FROM DEATH_CAUSES
WHERE YEAR = 2019;


--Selecting country with highest SELF_HARM
SELECT ENTITY, YEAR , SELF_HARM
FROM DEATH_CAUSES
WHERE YEAR = 2019
ORDER BY SELF_HARM desc;


--Selecting country with highest INTERPERSONAL_VIOLENCE
SELECT ENTITY, YEAR , INTERPERSONAL_VIOLENCE
FROM DEATH_CAUSES
WHERE YEAR = 2019
ORDER BY INTERPERSONAL_VIOLENCE desc;


--Selecting country with highest MALARIA
SELECT ENTITY, YEAR , MALARIA
FROM DEATH_CAUSES
WHERE YEAR = 2019
ORDER BY MALARIA desc;


--Selecting country with highest HIV_AIDS
SELECT ENTITY, YEAR , HIV_AIDS
FROM DEATH_CAUSES
WHERE YEAR = 2019
ORDER BY HIV_AIDS desc;


--South Africa stats
SELECT ENTITY, SUM(SELF_HARM) as TotalSelf_Harm, SUM(INTERPERSONAL_VIOLENCE) as Homocide, SUM(BURNT) as Burnt, SUM(DRUG_USE_DISORDERS) as Drug_Overdose, SUM(ALCOHOL_USE_DISORDERS) as Alcohol_Overdose, SUM(HIV_AIDS) as HIV_AIDS, SUM(TUBERCULOSIS) as TB
FROM DEATH_CAUSES
WHERE ENTITY = 'South Africa'
GROUP BY ENTITY
ORDER BY TOTALSELF_HARM desc;


--Showing the total sum of self_harm, drug_overdose etc
SELECT ENTITY, SUM(SELF_HARM) as TotalSelf_Harm, SUM(INTERPERSONAL_VIOLENCE) as Homocide, SUM(BURNT) as Burnt, SUM(DRUG_USE_DISORDERS) as Drug_Overdose, SUM(ALCOHOL_USE_DISORDERS) as Alcohol_Overdose, SUM(HIV_AIDS) as HIV_AIDS, SUM(TUBERCULOSIS) as TB
FROM DEATH_CAUSES
GROUP BY ENTITY
ORDER BY TOTALSELF_HARM desc;


DROP TABLE DEATH_CAUSES;
DROP TABLE DEATH_CAUSES1;